# Generated by Django 5.2.11 on 2026-02-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('std_id', models.IntegerField(unique=True)),
                ('age', models.IntegerField(max_length=3)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('dob', models.DateField()),
                ('dept', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_img/')),
            ],
        ),
    ]
